"""Generates docs/reference/principle-map.md: which principle is enforced by what, and where.

Answers the question the annotations exist to make answerable - "what actually implements P-071?" -
from the code rather than from memory, and reports principles that nothing enforces or implements
so the gap is visible instead of assumed.
"""

import os
import re
import sys

PRINCIPLES_DIR = "docs/principles"
RULES_DIR = "libs/arch-test/src/main/java/com/acme/archtest"
OUTPUT = "docs/reference/principle-map.md"
SOURCE_ROOTS = ("libs", "services")

# Some principles are enforced outside compiled code, so ArchUnit cannot see them. These are the
# scripts CI runs for them; listed here so the map credits real enforcement rather than reporting
# a gap that does not exist.
SCRIPT_ENFORCED = {
    "P-000": ["tools/check-doc-links.sh", "tools/check-rule-references.sh"],
    "P-050": ["tools/check-error-codes.sh"],
    "P-080": ["tools/check-error-codes.sh"],
    "P-110": ["tools/check-migrations.sh"],
    "P-112": ["tools/check-migrations.sh"],
}

PRINCIPLE_ID = re.compile(r"^(P-\d{3})-(.+)\.md$")
TITLE = re.compile(r"^#\s*(P-\d{3})\s*[-—]\s*(.+)$")


def principles() -> dict[str, tuple[str, str]]:
    found = {}
    for name in sorted(os.listdir(PRINCIPLES_DIR)):
        match = PRINCIPLE_ID.match(name)
        if not match:
            continue
        title = match.group(2).replace("-", " ")
        with open(os.path.join(PRINCIPLES_DIR, name), encoding="utf-8") as handle:
            for line in handle:
                heading = TITLE.match(line.strip())
                if heading:
                    title = heading.group(2).strip()
                    break
        found[match.group(1)] = (name, title)
    return found


def rules_by_principle() -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = {}
    for name in sorted(os.listdir(RULES_DIR)):
        if not name.endswith("Rules.java"):
            continue
        cls = name[: -len(".java")]
        text = open(os.path.join(RULES_DIR, name), encoding="utf-8").read()
        # Each rule's .as("… (P-0NN)") names the principle it enforces.
        for rule, description in re.findall(r"ArchRule\s+([a-zA-Z0-9]+)\s*=(.*?);\s*\n", text, re.S):
            for principle in set(re.findall(r"\((P-\d{3})\)", description)):
                mapping.setdefault(principle, []).append(f"{cls}.{rule}")
        for rule, body in re.findall(r"static\s+void\s+([a-zA-Z0-9]+)\s*\(JavaClasses[^)]*\)\s*\{(.*?)\n    \}", text, re.S):
            for principle in set(re.findall(r"(P-\d{3})", body)):
                mapping.setdefault(principle, []).append(f"{cls}.{rule}")
    return mapping


def claims_in_code() -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = {}
    for root_dir in SOURCE_ROOTS:
        for root, dirs, files in os.walk(root_dir):
            dirs[:] = [d for d in dirs if d not in {"target", ".git"}]
            for name in files:
                if not name.endswith(".java"):
                    continue
                path = os.path.join(root, name)
                text = open(path, encoding="utf-8", errors="ignore").read()
                for block in re.findall(r"@ImplementsPrinciple\s*\((.*?)\)", text, re.S):
                    for principle in set(re.findall(r"(P-\d{3})", block)):
                        mapping.setdefault(principle, []).append(name[: -len(".java")])
    return mapping


def main() -> int:
    known = principles()
    rules = rules_by_principle()
    claims = claims_in_code()

    lines = [
        "# Principle map",
        "",
        "**Generated by `tools/principle-map.sh`. Do not edit by hand.**",
        "",
        "What enforces each principle, and what claims to implement it. A principle with no rule and",
        "no claim is not necessarily wrong - some cannot be mechanised - but it is the list worth",
        "reviewing, because those are the rules that decay without anyone noticing.",
        "",
        "| Principle | Title | Enforced by | Claimed by |",
        "|---|---|---|---|",
    ]
    unenforced = []
    for principle, (filename, title) in sorted(known.items()):
        enforcing = sorted(set(rules.get(principle, []))) + SCRIPT_ENFORCED.get(principle, [])
        claiming = sorted(set(claims.get(principle, [])))
        if not enforcing:
            unenforced.append(f"{principle} {title}")
        lines.append(
            "| [{p}]({d}/{f}) | {t} | {e} | {c} |".format(
                p=principle,
                d="../principles",
                f=filename,
                t=title,
                e=", ".join(f"`{r}`" for r in enforcing) or "_review only_",
                c=", ".join(f"`{c}`" for c in claiming) or "—",
            )
        )

    lines += [
        "",
        "## Not mechanically enforced",
        "",
        "These rely on review. That is a deliberate choice in each case - the rule needs judgement, or",
        "lives outside compiled code - but the list should stay short, and shrink when someone finds a",
        "way to check one.",
        "",
    ]
    lines += [f"- {entry}" for entry in unenforced] or ["- (none)"]
    lines.append("")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"Wrote {OUTPUT}: {len(known)} principles, {len(unenforced)} not mechanically enforced.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
